language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose up
  - docker tag udagram-api-feed reubenvm/udagram-api-feed:v1
  - docker tag udagram-api-user reubenvm/udagram-api-user:v1
  - docker tag udagram-frontend reubenvm/udagram-frontend:v1
  - docker tag reverseproxy reubenvm/reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push reubenvm/udagram-api-feed:v1
  - docker push reubenvm/udagram-api-user:v1
  - docker push reubenvm/udagram-frontend:v1
  - docker push reubenvm/reverseproxy:v1
